### ISSUE TITLE
Deprecation candidate?

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-react#12]
This stood as a good introduction to using Origami with React, and was something we could point to.

However these days I know some of us are more likely to point to @taktran's [work on spark-lists](https://github.com/Financial-Times/spark-lists/tree/master/src/client/components/Origami#origami-react-components).

This repo, origami-react, hasn't seen an update in 2 years and React has seen a lot of changes since then. We're probably not going to maintain this, so shall we shelve it?

**Comment by JakeChampion** [comment]
I vote in favour of shelving it 👍
